# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        thumbnail_medium:
            filters:
                thumbnail: { size: [300, 300], mode: outbound, upscale: true}
        thumbnail_small:
            filters:
                thumbnail: { size: [200, 200], mode: outbound, allow_upscale: true}
        thumbnail_big:
            filters:
                thumbnail: { size: [800, 800], mode: outbound, allow_upscale: true}