vich_uploader:
    db_driver: orm

    mappings:
        tattoo_image:
            uri_prefix: /uploads/tattoos
            upload_destination: '%kernel.project_dir%/public/uploads/tattoos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true